"""add concept creation_seq and overruled_prerequisites

Revision ID: 29ddf3bc9c06
Revises: 
Create Date: 2026-06-10 17:33:19.720476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ddf3bc9c06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overruled_prerequisites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prereq_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['prereq_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Plain ADD COLUMN ... GENERATED BY DEFAULT AS IDENTITY backfills existing rows
    # sequentially (Postgres 10+) and is equivalent to BIGSERIAL.
    op.execute("ALTER TABLE concepts ADD COLUMN creation_seq BIGINT GENERATED BY DEFAULT AS IDENTITY")
    op.create_unique_constraint('uq_concepts_creation_seq', 'concepts', ['creation_seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_concepts_creation_seq', 'concepts', type_='unique')
    op.drop_column('concepts', 'creation_seq')
    op.drop_table('overruled_prerequisites')
    # ### end Alembic commands ###
